### ISSUE TITLE
Doesn't support `#define THING`

### ISSUE THREAD

**Issue by AndrewRayCode** [dy/prepr#4]
I believe this is valid in glsl:

```glsl
#define THING
#ifdef THING
...
#end
```
But this raises
 > Error: Macro definition "#define THING" is malformed

**Comment by dy** [comment]
Is the `#define THING` correct?
I followed https://gcc.gnu.org/onlinedocs/cpp/Macros.html and did not find anything like that.
What is the expected result? `THING === true`?

**Comment by AndrewRayCode** [comment]
It's valid. It doesn't expand, it's just used for future `#ifdef` etc checks. For example search http://tigcc.ticalc.org/doc/cpp.html for `FILE_FOO_SEEN`

edit: https://gcc.gnu.org/onlinedocs/cpp/Once-Only-Headers.html#Once-Only-Headers

**Comment by dy** [comment]
Should be fixed in 4c88adb48e7ccf196906339040ea4b398d303605
