### ISSUE TITLE
Doesn't support `#if defined`

### ISSUE THREAD

**Issue by AndrewRayCode** [dy/prepr#6]
```javascript
    console.log(
      prepr(`
#define A 1
#if defined( A )
uniform float yes;
#endif
uniform float end;
    `)
    );
```

This outputs only
```
uniform float end;
```

I'm not sure if it's a separate problem, but it also doesn't handle static conditionals like `#if defined( A ) || defined( B )`

**Comment by dy** [comment]
Should be fixed in 56c3de6

**Comment by AndrewRayCode** [comment]
nice!

**Comment by dy** [comment]
Thanks for the reports btw!
