### ISSUE TITLE
Macros appear to be broken

### ISSUE THREAD

**Issue by themikelester** [dy/prepr#8]
It seems like macros are not being parsed. Executing the following sample code from the Readme: 

```
prepr(`
	#define A 2;

	#ifdef A
	var a = A;
	#endif

	#if A > 40
	//too far
	#elif A < 1
	//too close
	#else
	//about right
	#endif

	var b = myVar;
	var c = myMacro('xyz');
`, {
	myVar: 1,
	myMacro: function (arg) { return arg; }
});
```

results in an output of:

```




var a = 2;;



//about right

]]
var b = 1;
var c = myMacro('xyz');
```

You'll notice that `myMacro` has not been removed.

**Comment by themikelester** [comment]
It seems that the `parenthesis` package has changed the way that it formats the result object. When `flat` is true, it adds the `escape` string to the front AND the back of the match index. So instead of `___1` for the first match, it is now `___1___`. This seems to be undocumented as the README for parenthesis still lists the original behaviour. 

I've fixed this locally by changing the regex on line 126 to:
`var re = new RegExp(name + '\\s*\\(___([0-9]+)___\\)', 'g');`

**Comment by dy** [comment]
Thanks for the point. Fixed.
